# Generated by Django 4.2.4 on 2023-09-24 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=25)),
                ('body', models.TextField(max_length=20000)),
                ('status', models.CharField(choices=[('d', 'Delete'), ('ip', 'in_process'), ('p', 'Published')], max_length=20)),
                ('data_reverse', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='any_user', max_length=25)),
                ('main_text', models.TextField(max_length=1000)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.articles')),
            ],
        ),
    ]
